version: '3.7'
services:
  app:
    image: ghcr.io/yanni8/m347-devcontainer/devcontainer:latest

    container_name: devcontainerApp
    ports:
      - "8080:8000"
    networks:
      - dev-network
    depends_on:
      - database
    hostname: app
    env_file: "../.env"
    volumes:
      - ..:/app/code:cached

  database:
    image: mysql:5.7
    ports:
      - "3306:3306"
    expose:
      - "3306"
    container_name: devcontainerDb
    networks:
      - dev-network
    hostname: database

    env_file: "../.env"

  phpmyadmin:
    image: phpmyadmin:5
    env_file: "../.env"
    environment:
      - PMA_HOST=database
    ports:
      - "8081:80"

networks:
  dev-network:
    driver: bridge