version: '3.7'
services:
  app:
    image: ghcr.io/yanni8/m347-devcontainer/devcontainer:latest

    container_name: devcontainerApp
    ports:
      - "8080:8000"
    networks:
      - dev-network
    depends_on:
      - database
    hostname: app
    env_file: "../.env"
    volumes:
      - ..:/app:cached

  database:
    image: mysql:5.7
    ports:
      - "3306:3306"
    expose:
      - "3306"
    container_name: devcontainerDb
    networks:
      - dev-network
    hostname: db

    env_file: "../.env"

networks:
  dev-network:
    driver: bridge