version: '3.7'
services:
  app:
    image: ghcr.io/yanni8/m347-devcontainer/app:latest

    container_name: app
    ports:
      - "8080:8000"
    networks:
      - dev-network
    depends_on:
      - database
    hostname: app
    env_file: "./.env"

  database:
    image: mysql:5.7
    ports:
      - "3306:3306"
    expose:
      - "3306"
    container_name: database
    networks:
      - dev-network
    hostname: db

    env_file: "./.env"

networks:
  dev-network:
    driver: bridge